apiVersion: v1
kind: ServiceAccount
metadata:
  name: streamforge
  namespace: streamforge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: streamforge-role
  namespace: streamforge
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: streamforge-rolebinding
  namespace: streamforge
subjects:
  - kind: ServiceAccount
    name: streamforge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: streamforge-role
