apiVersion: v1
kind: Service
metadata:
  name: streamforge-ingest
spec:
  type: {{ .Values.ingest.service.type }}
  selector:
    app: streamforge-ingest
  ports:
    - name: http
      port: {{ .Values.ingest.service.port }}
      targetPort: 8080
