{{- if .Values.ingest.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamforge-ingest
spec:
  ingressClassName: {{ .Values.ingest.ingress.className }}
  rules:
    - host: {{ .Values.ingest.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: streamforge-ingest
                port:
                  number: {{ .Values.ingest.service.port }}
{{- end }}
